version: '3'
services:
  mongo:
    image: tutum/mongodb
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      - AUTH=no
    volumes:
      - ./mongo-data:/data/db